version: "3.8"
services:
  brain:
    build:
      args:
        NETWORK: gnosis

  web3signer:
    build:
      args:
        NETWORK: gnosis
        PGPASSWORD: gnosis
        POSTGRES_DB: web3signer-gnosis
    healthcheck:
      test: >-
        curl -H 'Host: web3signer.web3signer-gnosis.dappnode'
        http://localhost:9000/healthcheck
      interval: 5s
      timeout: 5s
      retries: 100

  flyway:
    build:
      args:
        NETWORK: gnosis
        PGPASSWORD: gnosis
        POSTGRES_DB: web3signer-gnosis

  postgres:
    build:
      dockerfile: Dockerfile.debian
      args:
        POSTGRES_PASSWORD: gnosis
        PGPASSWORD: gnosis
        POSTGRES_DB: web3signer-gnosis
