name: "Build Test on all networks"
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build test
    steps:
      - uses: actions/checkout@v4
      - run: npx @dappnode/dappnodesdk build --skip_save --all-variants --content_provider=http://10.200.200.7:5001 --eth_provider=https://web3.dappnode.net